server:
    port: 8082

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 12345
        url: jdbc:mysql://localhost:3306/pms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true

mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl